drop function if exists public.increment_org_quota(uuid);
drop view if exists public.org_usage_this_month;
drop trigger if exists trg_step_runs_org_id on public.step_runs;
drop function if exists public.set_org_id_from_run();
drop trigger if exists trg_runs_org_id on public.workflow_runs;
drop trigger if exists trg_triggers_org_id on public.workflow_triggers;
drop trigger if exists trg_steps_org_id on public.workflow_steps;
drop function if exists public.set_org_id_from_workflow();
drop table if exists public.step_runs;
drop table if exists public.workflow_runs;
drop table if exists public.workflow_triggers;
drop table if exists public.workflow_steps;
drop table if exists public.workflows;
drop table if exists public.org_members;
drop table if exists public.organizations;
drop type if exists public.step_run_status;
drop type if exists public.run_status;
drop type if exists public.trigger_type;
drop type if exists public.step_type;
drop type if exists public.member_role;
